apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-service
  template:
    metadata:
      labels:
        app: register-service
    spec:
      containers:
        - name: register-service
          image: register-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
