apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: login-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8000/tokens"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
