apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: my-gateway
  namespace: projectcontour
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: contour
  listeners:
    - name: https
      hostname: api.danielcortes.dev
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: tls-secret
          - kind: Secret
          - group: core
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
    - name: rtmp
      hostname: stream.danielcortes.dev
      protocol: TCP
      port: 1935
      allowedRoutes:
        kinds:
          - kind: TCPRoute
        namespaces:
          from: All
