apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-admin-username: cG9zdGdyZXNfYWRtaW4= # 'postgres_admin' en base64
  postgres-password: YWRtaW5wYXNzd29yZA== # 'adminpassword' en base64
