apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-admin-username: bW9uZ29fYWRtaW4= # 'mongo_admin' en base64
  mongo-password: YWRtaW5wYXNzd29yZA== # 'adminpassword' en base64
