apiVersion: v1
kind: PersistentVolume
metadata:
  name: hls-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: hls-pvc
  hostPath:
    path: /mnt/data/transcoded-data
