apiVersion: v1
kind: PersistentVolume
metadata:
  name: record-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: record-pvc
  hostPath:
    path: /mnt/data/recorded-data
