apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values for sensitive information
  POSTGRES_URL: cG9zdGdyZXM6Ly9wc19hZG1pbjphZG1pbnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvc3RyZWFtX3VzZXJz # postgres://ps_admin:adminpassword@postgres:5432/stream_users
  JWT_SECRET: YjQyYWU1ZjQxZmFhZGQzN2Q2MzIyYzMwYWFiMDc5MzAyZDI1MjFmZWI5YzhjNTE4ODJjYWFjN2UzNGE4ZDkzMA== # b42ae5f41faadd37d6322c30aab079302d2521feb9c8c51882caac7e34a8d930
  MONGO_URL: bW9uZ29kYjovL21vbmdvX2FkbWluOmFkbWlucGFzc3dvcmRAbW9uZ286MjcwMTc= # mongodb://mongo_admin:adminpassword@mongo:27017
