apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmuxing-service
  labels:
    app: transmuxing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmuxing-service
  template:
    metadata:
      labels:
        app: transmuxing-service
    spec:
      containers:
      - name: transmuxing-service
        image: transmuxing-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: HLS_SEGMENT_TIME
          value: "4"
        - name: HLS_LIST_SIZE
          value: "3"
        - name: RTMP_INPUT_BASE
          value: "rtmp://rtmp-ingest-service/live/"
        - name: HLS_OUTPUT_BASE
          value: "/tmp/hls/"
        - name: RECORDING_OUTPUT_BASE
          value: "/tmp/recordings/"
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URL
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8000"
        - name: TRANSCODING_SERVICE_URL
          value: "http://transcoding-service:8000"
        - name: STREAM_INFORMATION_SERVICE_URL
          value: "http://stream-information-service:8000"
        volumeMounts:
        - name: hls-data
          mountPath: /tmp/hls
        - name: recording-data
          mountPath: /tmp/recordings
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "3"
          limits:
            memory: "3Gi"
            cpu: "4"
      volumes:
      - name: hls-data
        persistentVolumeClaim:
          claimName: hls-pvc
      - name: recording-data
        persistentVolumeClaim:
          claimName: record-pvc
