apiVersion: apps/v1
kind: Deployment
metadata:
  name: hls-distribution-service
  labels:
    app: hls-distribution-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hls-distribution-service
  template:
    metadata:
      labels:
        app: hls-distribution-service
    spec:
      containers:
      - name: hls-distribution-service
        image: hls-distribution-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: HLS_STREAM_BASE
          value: /tmp/hls
        - name: RECORDING_BASE
          value: /tmp/recordings
        volumeMounts:
        - name: hls-data
          mountPath: /tmp/hls
        - name: record-data
          mountPath: /tmp/recordings
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: hls-data
        persistentVolumeClaim:
          claimName: hls-pvc
      - name: record-data
        persistentVolumeClaim:
          claimName: record-pvc
