apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-information-service
  labels:
    app: stream-information-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-information-service
  template:
    metadata:
      labels:
        app: stream-information-service
    spec:
      containers:
      - name: stream-information-service
        image: stream-information-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MONGO_URL
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8000"
        - name: USER_SERVICE_URL
          value: "http://user-service:8000"
        - name: TRANSMUXING_SERVICE_URL
          value: "http://transmuxing-service:8000"
        - name: TRANSCODING_SERVICE_URL
          value: "http://transcoding-service:8000"
        - name: HLS_BASE_PATH
          value: "/tmp/hls/"
        - name: RECORDING_BASE_PATH
          value: "/tmp/recordings/"
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_URL
        volumeMounts:
        - name: hls-data
          mountPath: /tmp/hls/
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: hls-data
        persistentVolumeClaim:
          claimName: hls-pvc
