apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stream-information-routes
spec:
  parentRefs:
  - name: my-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /streams/
    - path:
        type: PathPrefix
        value: /search/livestreams
      method: GET
    - path:
        type: PathPrefix
        value: /search/vods
      method: GET
    - path:
        type: PathPrefix
        value: /search/livestreams
      method: OPTIONS
    - path:
        type: PathPrefix
        value: /search/vods
      method: OPTIONS
    backendRefs:
    - name: stream-information-service
      port: 8000
